name = "GalacticOptim"
uuid = "a75be94c-b780-496d-a8a9-0878b188d577"
authors = ["Vaibhavdixit02 <vaibhavyashdixit@gmail.com>"]
version = "0.1.3"

[deps]
ConsoleProgressMonitor = "88cd18e8-d9cc-4ea6-8889-5259c0d15c8b"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ConsoleProgressMonitor = "0.1"
DiffEqBase = "6.41"
DiffResults = "1.0"
FiniteDiff = "2.5"
Flux = "0.11"
ForwardDiff = "0.10"
LoggingExtras = "0.4"
Optim = "0.22"
ProgressLogging = "0.1"
Requires = "1.0"
ReverseDiff = "1.4"
TerminalLoggers = "0.1"
Tracker = "0.2"
Zygote = "0.5"
julia = "1.3"

[extras]
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
CMAEvolutionStrategy = "8d3b24bd-414e-49e0-94fb-163cc3a3e411"
Evolutionary = "86b6b26d-c046-49b6-aa0b-5f0f74682bd6"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BlackBoxOptim", "Evolutionary", "NLopt", "CMAEvolutionStrategy", "Test"]
