name = "GalacticOptim"
uuid = "a75be94c-b780-496d-a8a9-0878b188d577"
authors = ["Vaibhavdixit02 <vaibhavyashdixit@gmail.com>"]
version = "0.1.2"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
DiffEqBase = "6.41"
DiffResults = "1.0"
ForwardDiff = "0.10"
Optim = "0.22"
Requires = "1.0"
Zygote = "0.5"
julia = "1"

[extras]
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
Evolutionary = "86b6b26d-c046-49b6-aa0b-5f0f74682bd6"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BlackBoxOptim", "Evolutionary", "NLopt", "Test"]
