name = "GalacticMetaheuristics"
uuid = "ea53b4ef-d776-41ba-b3a2-ff4f1ca97632"
authors = ["Vaibhav Dixit <vaibhavyashdixit@gmail.com> and contributors"]
version = "0.1.0"

[deps]
GalacticOptim = "a75be94c-b780-496d-a8a9-0878b188d577"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
