[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
AmplNLWriter = "7c4d4715-977e-5154-bfe0-e096adeac482"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Ipopt_jll = "9cc047cb-c261-5740-88fc-0cf96f7bdcc7"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
Manopt = "0fc0a36d-df90-57f3-8f93-d78a9fc72bb5"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsTest = "7998695d-6960-4d3a-85c4-e1bceb8cd856"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationBase = "bca83a33-5cc9-4baa-983d-23429ab6bcbb"
OptimizationCMAEvolutionStrategy = "bd407f91-200f-4536-9381-e4ba712f53f8"
OptimizationEvolutionary = "cb963754-43f6-435e-8d4b-99009ff27753"
OptimizationGCMAES = "6f0a0517-dbc2-4a7a-8a20-99ae7f27e911"
OptimizationIpopt = "43fad042-7963-4b32-ab19-e2a4f9a67124"
OptimizationLBFGSB = "22f7324a-a79d-40f2-bebe-3af60c77bd15"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
OptimizationManopt = "e57b7fff-7ee7-4550-b4f0-90e9476e9fb6"
OptimizationMetaheuristics = "3aafef2f-86ae-4776-b337-85a36adf0b55"
OptimizationNLPModels = "064b21be-54cf-11ef-1646-cdfee32b588f"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
OptimizationNOMAD = "2cab0595-8222-4775-b714-9828e6a9e01b"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
OptimizationPRIMA = "72f8369c-a2ea-4298-9126-56167ce9cbc2"
OptimizationPolyalgorithms = "500b13db-7e66-49ce-bda4-eed966be6282"
OptimizationSpeedMapping = "3d669222-0d7d-4eb9-8a9f-d8528b0d9b91"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
SymbolicAnalysis = "4297ee4d-0239-47d8-ba5d-195ecdf594fe"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[sources]
Optimization = {path = ".."}
OptimizationBBO = {path = "../lib/OptimizationBBO"}
OptimizationBase = {path = "../lib/OptimizationBase"}
OptimizationCMAEvolutionStrategy = {path = "../lib/OptimizationCMAEvolutionStrategy"}
OptimizationEvolutionary = {path = "../lib/OptimizationEvolutionary"}
OptimizationGCMAES = {path = "../lib/OptimizationGCMAES"}
OptimizationIpopt = {path = "../lib/OptimizationIpopt"}
OptimizationLBFGSB = {path = "../lib/OptimizationLBFGSB"}
OptimizationMOI = {path = "../lib/OptimizationMOI"}
OptimizationManopt = {path = "../lib/OptimizationManopt"}
OptimizationMetaheuristics = {path = "../lib/OptimizationMetaheuristics"}
OptimizationNLPModels = {path = "../lib/OptimizationNLPModels"}
OptimizationNLopt = {path = "../lib/OptimizationNLopt"}
OptimizationNOMAD = {path = "../lib/OptimizationNOMAD"}
OptimizationOptimJL = {path = "../lib/OptimizationOptimJL"}
OptimizationOptimisers = {path = "../lib/OptimizationOptimisers"}
OptimizationPRIMA = {path = "../lib/OptimizationPRIMA"}
OptimizationPolyalgorithms = {path = "../lib/OptimizationPolyalgorithms"}
OptimizationSpeedMapping = {path = "../lib/OptimizationSpeedMapping"}

[compat]
ADTypes = "1"
AmplNLWriter = "1"
ComponentArrays = "0.15"
Documenter = "1"
FiniteDiff = ">= 2.8.1"
ForwardDiff = ">= 0.10.19"
HiGHS = "1"
Ipopt = "1"
IterTools = "1"
Juniper = "0.9"
Lux = "1"
MLUtils = "0.4.4"
Manifolds = "0.10"
Manopt = "0.5"
ModelingToolkit = "10.23"
NLPModels = "0.21"
NLPModelsTest = "0.10"
NLopt = "0.6, 1"
Optimization = "5"
OptimizationBBO = "0.4"
OptimizationBase = "4"
OptimizationCMAEvolutionStrategy = "0.3"
OptimizationEvolutionary = "0.4"
OptimizationGCMAES = "0.3"
OptimizationIpopt = "0.2"
OptimizationMOI = "0.5"
OptimizationManopt = "1"
OptimizationMetaheuristics = "0.3"
OptimizationNLPModels = "0.0.2, 1"
OptimizationNLopt = "0.3"
OptimizationNOMAD = "0.3"
OptimizationOptimJL = "0.4"
OptimizationOptimisers = "0.3"
OptimizationPRIMA = "0.3"
OptimizationPolyalgorithms = "0.3"
OptimizationSpeedMapping = "0.2"
OrdinaryDiffEq = "6"
Plots = "1"
Random = "1"
ReverseDiff = ">= 1.9.0"
SciMLBase = "2.122.1"
SciMLSensitivity = "7"
SymbolicAnalysis = "0.3"
Symbolics = "6"
Tracker = ">= 0.2"
Zygote = ">= 0.5"
